### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by SomeUserName1** [midas-tum/merlin#7]
Hi,

I have a couple of questions about the installation of merlin.

1. gpuNUFFT
- Is gpuNUFFT neccessary to run the unit tests sucessfully? For what is it needed?
- Does one still have to compile it with gcc-4.6? (gcc-13.2 doen't compile without errors). How does that affect the nvcc version to be used?
I tried compiling with gcc-4.4 but that just yielded errors:
`cmake .. -DGEN_MEX_FILES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=gcc-4.4 -DCMAKE_CXX_COMPILER=g++-4.4`

```
-- The C compiler identification is GNU 4.4.7  
-- The CXX compiler identification is GNU 4.4.7  
-- Detecting C compiler ABI info  
-- Detecting C compiler ABI info - done  
-- Check for working C compiler: /usr/bin/gcc-4.4 - skipped  
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++-4.4 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found version "12.3") 
-- Setting DEBUG Option to false
add CUDA 8 flags: Current version: 12.3
add CUDA 9 flags: Current version: 12.3
add CUDA 10 flags: Current version: 12.3
-- setting NVCC FLAGS to: -arch=sm_50;-gencode;arch=compute_50,code=sm_50;-gencode=arch=compute_52,code=sm_52;-gencode=arch=compute_52,code=compute_52;-gencode=arch=compute_60,code=sm_60;-gencode=arch=compute_61,code=sm_61;-gencode=arch=compute_61,code=compute_61;-gencode=arch=compute_70,code=sm_70;-gencode=arch=compute_75,code=sm_75
-- creating lib with name: gpuNUFFT_ATM_f
------start creating libraries-------
Atomic GPU GpuNUFFT Library
-- Found PythonInterp: /home/someusername/workspace/UNet-bSSFP/unet-venv/bin/python3 (found suitable version "3.11.6", minimum required is "3.5") 
-- Found PythonLibs: /usr/lib/libpython3.11.so (found suitable version "3.11.6", minimum required is "3.5") 
-- Building Python interface
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /home/someusername/workspace/UNet-bSSFP/gpuNUFFT/CUDA/build
```
The output of `make`  including the errors is attached [out.txt](https://github.com/midas-tum/merlin/files/14200273/out.txt)

2. OptoX
- In another issue i read that it's possible to build merlin without OptoX. That's quite astonishing from the code (try except around the import and throwing an error in except)
- If I only want to use PyTorch, is it sufficient to build and install the PyTorch part of OptoX?

3. merlin
- With OptoX but without gpuNUFFT. 25/112 tests fail. Most of them with a RuntimeError similar to this: `RuntimeError: grad can be implicitly created only for real scalar outputs but got torch.complex64`
test_ssim and the batched version fail with: `ValueError: win_size exceeds image extent. Either ensure that your images are at least 7x7; or pass win_size explicitly in the function call, with an odd value less than or equal to the smaller side of your images. If your images are multichannel (with color channels), set channel_axis to the axis number corresponding to the channels.`

Is this related to not installing gpuNUFFT and OptoX properly or is something else wrong here?

Best,
Fabian

**Comment by SomeUserName1** [comment]
Regarding 1:

gpuNUFFT needs CUDA  < 12 as NVidia dropped support for texture references in favor of texture objects with the latest major revision . 
This also causes the "no instance of overloaded function" error as the overloaded version of tex1D for texture references was obv. removed, too.
I'll port to CUDA 12 and CMake 3.19 (for the find package related stuff wrt. CUDA & Python) and PR.

**Comment by thomaskuestner** [comment]
Hi Fabian,

thanks for your inputs.
1. Yes that is correct, we also noticed the change in CUDA 12.x and we still need to port gpuNUFFT to CUDA 12. Appreciated if you are already working on it.
2. This was (and should still be) supported to work with merlin without installing optox. However, you are limiting your possible operations then. I have noted down the "import" bug and we will address this with the next version. 

If you only want to use PyTorch, you can only install optoth.
3. Thanks for bringing this to our attention. It seems that PyTorch changed stuff here. I haven't seen this error before. We need to investigate it.

**Comment by SomeUserName1** [comment]
Notes/TODOs for my future self:
- the updated version of gpuNUFFT now builds correctly without compiler errors and warnings but 5/71 unit tests are still failing. No time to go through 14k loc to trace the issue now.
- OptoX unittests contain race conditions and 701 (not enough resources to start) according to NVidias compute sanitizer. Errors not detected as there's no error handling for some cuda calls.
- Merlin uses the tf v1 API which is deprecated and the unit tests don't work for v2 without adaptations
