### ISSUE TITLE
optoth and merlinth on torch >= 2.0

### ISSUE THREAD

**Issue by tonerbp** [midas-tum/merlin#8]
Is merlinth, in general, supported with torch version >= 2.0? I have trained models in the past using torch 1.10+cu111, but upgraded to torch 2.1+cu118 to use some packages only supported in torch >= 2.0. I can evaluate my merlinth models using torch 2.1, but when I try to continue training, after a single backprop step all the weights become NaN. I'm curious as to whether optoth/merlinth are compatible with the newer versions of pytorch. I see that in the setup.py file it only requires >= 1.0. I'm just not sure if this is something not currently supported at all or if there is something wrong with the way I am building. 

Thanks!

Best,
Brian

**Comment by tonerbp** [comment]
After some more testing I realize that this only occurs when I load a torch 1.10 model and try to continue training in torch 2.1. But it does not occur when I start training a torch 2.1 model from scratch. So I think this is a torch issue, not a merlinth one. Sorry for any confusion. Thank you for this fantastic package!

Best,
Brian

**Comment by thomaskuestner** [comment]
Good to hear! Thanks for letting us know.
